import { NgModule } from '@angular/core';
import {
  MatButtonModule,
  MatInputModule,
  MatSelectModule,
  MatIconModule,
  MatListModule,
  MatMenuModule,
  MatSidenavModule,
  MatToolbarModule,
  MatTabsModule,
  MatCardModule,
  MatAutocompleteModule,
  MatDialogModule,
  MatTableModule,
  MatSortModule,
  MatPaginatorModule,
  MatProgressBarModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatCheckboxModule,
  MatChipsModule,
  MatSlideToggleModule,
  MatButtonToggleModule,
  MatExpansionModule
} from '@angular/material';

@NgModule({
    imports: [
      MatButtonModule,
      MatInputModule,
      MatSelectModule,
      MatIconModule,
      MatListModule,
      MatMenuModule,
      MatSidenavModule,
      MatToolbarModule,
      MatTabsModule,
      MatCardModule,
      MatAutocompleteModule,
      MatDialogModule,
      MatTableModule,
      MatSortModule,
      MatPaginatorModule,
      MatProgressBarModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatCheckboxModule,
      MatChipsModule,
      MatSlideToggleModule,
      MatButtonToggleModule,
      MatExpansionModule
    ],
    exports: [
      MatButtonModule,
      MatInputModule,
      MatSelectModule,
      MatIconModule,
      MatListModule,
      MatMenuModule,
      MatSidenavModule,
      MatToolbarModule,
      MatTabsModule,
      MatCardModule,
      MatAutocompleteModule,
      MatDialogModule,
      MatTableModule,
      MatSortModule,
      MatPaginatorModule,
      MatProgressBarModule,
      MatDatepickerModule,
      MatNativeDateModule,
      MatCheckboxModule,
      MatChipsModule,
      MatSlideToggleModule,
      MatButtonToggleModule,
      MatExpansionModule
    ],
    providers: []
})
export class MaterialModule {}
